/*
 * This file was automatically generated by EvoSuite
 * Sun Sep 27 02:02:40 GMT 2026
 */

package ar.edu.unrc.game2048;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ar.edu.unrc.game2048.Board;
import ar.edu.unrc.game2048.Cell;
import ar.edu.unrc.game2048.MockRNG;
import ar.edu.unrc.game2048.RNG;
import ar.edu.unrc.game2048.RNGStrategy;
import java.util.NoSuchElementException;
import java.util.Set;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.Random;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Board_ESTest extends Board_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Board board0 = new Board(2, 2);
      Board board1 = new Board(board0);
      board1.moveUp();
      board0.equals(board1);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Board board0 = new Board(32, 32);
      board0.isFull();
      board0.isLosingBoard();
      board0.isLosingBoard();
      board0.isEmpty();
      board0.repOK();
      board0.moveRight();
      Cell cell0 = new Cell(32);
      board0.getSize();
      board0.getScore();
      Random.setNextRandom(13);
      board0.moveRight();
      // Undeclared exception!
      board0.moveLeft();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-167), 2232);
      board_Position0.toString();
      board_Position0.toString();
      Board.Position board_Position1 = new Board.Position((-167), (-167));
      board_Position1.toString();
      board_Position0.toString();
      board_Position1.toString();
      board_Position1.toString();
      board_Position0.equals(board_Position1);
      Board board0 = new Board();
      board0.moveDown();
      board0.isEmpty();
      board0.getSize();
      board0.initializeEmptyTest();
      board0.isLosingBoard();
      board0.equals(board0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-167), 2232);
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      Board.Position board_Position1 = new Board.Position((-167), (-167));
      board_Position1.toString();
      board_Position0.toString();
      board_Position1.toString();
      board_Position1.toString();
      board_Position0.equals(board_Position1);
      Board board0 = new Board();
      board0.moveDown();
      board0.isEmpty();
      board0.getSize();
      board0.initializeEmptyTest();
      board0.isLosingBoard();
      int int0 = Board.DEFAULT_WINNING_VALUE;
      Board board1 = new Board(board0);
      board0.equals(board1);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      RNG rNG0 = new RNG();
      Board board0 = new Board(rNG0, 1, 2);
      board0.getSize();
      rNG0.getRandom();
      rNG0.getRandom();
      board0.toString();
      board0.repOK();
      board0.hasEmptyCells();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      RNGStrategy rNGStrategy0 = null;
      Board board0 = null;
      try {
        board0 = new Board((RNGStrategy) null, 1, 1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Board board0 = new Board(1, 1);
      board0.isLosingBoard();
      board0.isLosingBoard();
      board0.isEmpty();
      board0.repOK();
      board0.moveUp();
      board0.moveDown();
      board0.moveRight();
      board0.isWinningBoard();
      board0.moveLeft();
      Set<Board.Position> set0 = board0.getEmptyPositions();
      board0.moveRight();
      board0.hashCode();
      board0.moveLeft();
      board0.hasEmptyCells();
      Board.Position board_Position0 = new Board.Position(4, 1);
      board_Position0.toString();
      board_Position0.equals(set0);
      board0.moveUp();
      board0.toString();
      board0.isEmpty();
      board0.moveDown();
      board0.moveDown();
      board0.getEmptyPositions();
      board0.isLosingBoard();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      MockRNG mockRNG0 = new MockRNG();
      mockRNG0.getRandom();
      Board board0 = new Board(mockRNG0);
      board0.repOK();
      mockRNG0.getRandom();
      Board.Position board_Position0 = new Board.Position(0, 587);
      board_Position0.toString();
      Object object0 = new Object();
      board0.equals(mockRNG0);
      mockRNG0.getRandom();
      board0.initializeEmptyTest();
      board0.initializeEmptyTest();
      board0.moveLeft();
      board0.moveLeft();
      board0.hasEmptyCells();
      mockRNG0.getRandom();
      board0.getEmptyPositions();
      board0.hasEmptyCells();
      board0.hasEmptyCells();
      board0.isLosingBoard();
      board0.getSize();
      board0.getEmptyPositions();
      board_Position0.equals(board_Position0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Board board0 = new Board(1, 1);
      board0.isLosingBoard();
      board0.isLosingBoard();
      board0.isEmpty();
      board0.isFull();
      board0.repOK();
      board0.moveUp();
      board0.isLosingBoard();
      // Undeclared exception!
      try { 
        board0.getCell(2, 1);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (2, 1) is out of bounds for board size 1
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      MockRNG mockRNG0 = new MockRNG();
      mockRNG0.getRandom();
      mockRNG0.getRandom();
      Board board0 = new Board(mockRNG0);
      board0.getEmptyPositions();
      board0.moveLeft();
      mockRNG0.getRandom();
      board0.isWinningBoard();
      int int0 = 0;
      board0.moveUp();
      board0.getCell(0, 0);
      mockRNG0.getRandom();
      mockRNG0.getRandom();
      // Undeclared exception!
      try { 
        board0.getCell(0, 1511);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (0, 1511) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      MockRNG mockRNG0 = new MockRNG();
      mockRNG0.getRandom();
      Board board0 = new Board(mockRNG0);
      board0.repOK();
      mockRNG0.getRandom();
      Board.Position board_Position0 = new Board.Position(0, 587);
      board_Position0.toString();
      Object object0 = new Object();
      board_Position0.equals(object0);
      board0.equals(mockRNG0);
      mockRNG0.getRandom();
      board0.initializeEmptyTest();
      board0.initializeEmptyTest();
      board0.moveLeft();
      board0.moveLeft();
      board0.hasEmptyCells();
      mockRNG0.getRandom();
      board0.getEmptyPositions();
      board0.hasEmptyCells();
      board0.hasEmptyCells();
      board0.isLosingBoard();
      board0.moveRight();
      board0.getEmptyPositions();
      Board.Position board_Position1 = new Board.Position(0, 2048);
      board_Position0.equals(board_Position1);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(3, (-2000));
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.equals((Object) null);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      MockRNG mockRNG0 = new MockRNG();
      Board board0 = new Board(mockRNG0);
      board0.moveDown();
      board0.isEmpty();
      board0.moveDown();
      board0.equals(mockRNG0);
      Board.Position board_Position0 = new Board.Position(2048, (-2784));
      board_Position0.toString();
      Board board1 = new Board();
      board0.equals(board1);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Board board0 = new Board(92);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Board board0 = new Board(1, 1);
      board0.isLosingBoard();
      board0.isLosingBoard();
      board0.isEmpty();
      board0.repOK();
      board0.moveUp();
      board0.isLosingBoard();
      Cell cell0 = new Cell(1);
      board0.moveRight();
      board0.moveLeft();
      Set<Board.Position> set0 = board0.getEmptyPositions();
      board0.moveRight();
      board0.hashCode();
      board0.moveLeft();
      board0.hasEmptyCells();
      Board.Position board_Position0 = new Board.Position(4, 1);
      board_Position0.toString();
      board_Position0.equals(set0);
      board0.moveUp();
      board0.toString();
      board0.isEmpty();
      board0.moveDown();
      board0.moveDown();
      board0.getEmptyPositions();
      board0.isLosingBoard();
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Board board0 = new Board(2, 2);
      Board board1 = new Board(board0);
      board1.repOK();
      board0.isWinningBoard();
      Board.Position board_Position0 = new Board.Position((-2319), 2048);
      // Undeclared exception!
      try { 
        board1.getCell((-1001), (-357913942));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (-1001, -357913942) is out of bounds for board size 2
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-167), 2232);
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      Board.Position board_Position1 = new Board.Position((-167), (-167));
      board_Position1.toString();
      board_Position1.toString();
      board_Position1.toString();
      board_Position1.toString();
      board_Position0.equals(board_Position1);
      Board board0 = new Board();
      board0.moveDown();
      board0.isEmpty();
      board0.getSize();
      board0.initializeEmptyTest();
      board0.isLosingBoard();
      board0.getScore();
      board0.moveDown();
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      MockRNG mockRNG0 = new MockRNG();
      int int0 = 2;
      mockRNG0.getRandom();
      Board board0 = new Board(mockRNG0, 2, 2);
      mockRNG0.getRandom();
      board0.repOK();
      mockRNG0.getRandom();
      board0.moveDown();
      // Undeclared exception!
      try { 
        board0.setCell(2, 0, (Cell) null);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (2, 0) is out of bounds for board size 2
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      int int0 = 28;
      Board board0 = new Board(28);
      board0.hasEmptyCells();
      board0.repOK();
      board0.getEmptyPositions();
      board0.moveLeft();
      board0.moveDown();
      board0.toString();
      board0.getSize();
      board0.isFull();
      board0.getScore();
      board0.moveRight();
      board0.initializeEmptyTest();
      board0.hashCode();
      board0.hashCode();
      // Undeclared exception!
      board0.moveUp();
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Board board0 = new Board(278, 1);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board((Board) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Board board0 = new Board(1, 1);
      board0.isLosingBoard();
      board0.isLosingBoard();
      board0.isEmpty();
      board0.repOK();
      board0.moveUp();
      board0.isLosingBoard();
      // Undeclared exception!
      try { 
        board0.getCell(2, 1);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (2, 1) is out of bounds for board size 1
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Board board0 = new Board();
      board0.isWinningBoard();
      board0.initializeEmptyTest();
      board0.getEmptyPositions();
      board0.isLosingBoard();
      board0.repOK();
      board0.isEmpty();
      board0.repOK();
      Cell cell0 = Cell.EMPTY;
      // Undeclared exception!
      try { 
        board0.setCell(3, (-4869), cell0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (3, -4869) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      MockRNG mockRNG0 = new MockRNG();
      Board board0 = new Board(mockRNG0, 2048, 2048);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Board board0 = new Board();
      board0.toString();
      board0.isLosingBoard();
      board0.moveUp();
      board0.isFull();
      board0.getEmptyPositions();
      board0.getScore();
      board0.isLosingBoard();
      board0.moveRight();
      board0.getSize();
      board0.moveLeft();
      board0.moveLeft();
      board0.isLosingBoard();
      board0.getEmptyPositions();
      board0.isLosingBoard();
      board0.initializeEmptyTest();
      board0.moveUp();
      board0.initializeEmptyTest();
      board0.getScore();
      board0.moveDown();
      board0.toString();
      board0.isLosingBoard();
      board0.getEmptyPositions();
      board0.moveUp();
      board0.repOK();
      board0.moveUp();
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      MockRNG mockRNG0 = new MockRNG();
      mockRNG0.getRandom();
      mockRNG0.getRandom();
      mockRNG0.getRandom();
      mockRNG0.getRandom();
      Board board0 = new Board(mockRNG0);
      board0.moveUp();
      mockRNG0.getRandom();
      board0.getSize();
      board0.hashCode();
      mockRNG0.getRandom();
      Board.Position board_Position0 = new Board.Position(2048, 0);
      board_Position0.toString();
      board_Position0.toString();
      // Undeclared exception!
      try { 
        board0.getCell(0, 4);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (0, 4) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Board board0 = new Board();
      board0.moveLeft();
      board0.hashCode();
      board0.isFull();
      board0.getEmptyPositions();
      // Undeclared exception!
      try { 
        board0.setCell(1, 0, (Cell) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cell cannot be null
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-44), (-44));
      Object object0 = new Object();
      board_Position0.equals(object0);
      Board board0 = null;
      try {
        board0 = new Board((MockRNG) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Board board0 = new Board();
      board0.equals((Object) null);
      board0.toString();
      Board.Position board_Position0 = new Board.Position(1217, (-2267));
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      board0.getSize();
      board0.hashCode();
      board0.moveRight();
      board0.isLosingBoard();
      board0.isLosingBoard();
      board0.moveRight();
      board0.initializeEmptyTest();
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      MockRNG mockRNG0 = new MockRNG(1.0);
      mockRNG0.getRandom();
      mockRNG0.getRandom();
      mockRNG0.getRandom();
      Board board0 = null;
      try {
        board0 = new Board(mockRNG0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No value present
         //
         verifyException("java.util.Optional", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      MockRNG mockRNG0 = new MockRNG();
      Board board0 = null;
      try {
        board0 = new Board(mockRNG0, 135, 135);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Winning value must be a power of two: 135
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Board board0 = new Board();
      board0.moveUp();
      board0.moveDown();
      Board board1 = new Board(board0);
      board0.moveRight();
      board0.moveLeft();
      board0.repOK();
      board1.moveLeft();
      board0.getScore();
      board1.getScore();
      board0.getEmptyPositions();
      board1.moveLeft();
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Board board0 = new Board();
      board0.moveDown();
      board0.getCell(1, 1);
      board0.equals((Object) null);
      board0.moveLeft();
      board0.initializeEmptyTest();
      board0.moveDown();
      board0.isEmpty();
      Board board1 = null;
      try {
        board1 = new Board(388, 3);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Winning value must be a power of two: 3
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(0, 0);
      Board board0 = new Board();
      board_Position0.toString();
      // Undeclared exception!
      try { 
        board0.getCell(0, 2501);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (0, 2501) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      int int0 = 1057;
      Board board0 = new Board(1057);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      MockRNG mockRNG0 = new MockRNG();
      mockRNG0.getRandom();
      Board board0 = new Board(mockRNG0);
      board0.moveUp();
      board0.isFull();
      board0.getScore();
      Cell cell0 = board0.getCell(0, 0);
      board0.getEmptyPositions();
      cell0.repOK();
      board0.setCell(0, 0, cell0);
      board0.equals(cell0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Board board0 = new Board();
      board0.getScore();
      board0.getEmptyPositions();
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-167), 2232);
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      Board.Position board_Position1 = new Board.Position(106, 106);
      board_Position1.toString();
      board_Position1.toString();
      board_Position1.toString();
      board_Position0.equals(board_Position1);
      Board board0 = new Board();
      board0.moveDown();
      board0.isEmpty();
      board0.isFull();
      board0.getSize();
      board0.initializeEmptyTest();
      board0.isLosingBoard();
      board0.getScore();
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Board board0 = new Board();
      Board board1 = new Board(board0);
      board1.moveDown();
      board1.isLosingBoard();
      Board.Position board_Position0 = new Board.Position(2048, 2036);
      board_Position0.toString();
      Board.Position board_Position1 = new Board.Position(2048, 2036);
      board1.moveUp();
      board_Position0.equals(board_Position1);
      Board board2 = new Board(4);
      board0.equals(board2);
      board1.isFull();
      board_Position1.equals("(2048, 2036)");
      board1.getSize();
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-1223), (-1223));
      board_Position0.equals("_aoM");
      Object object0 = new Object();
      board_Position0.equals(object0);
      MockRNG mockRNG0 = null;
      try {
        mockRNG0 = new MockRNG((-1223));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Value must be between 0 and 1
         //
         verifyException("ar.edu.unrc.game2048.MockRNG", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      int int0 = 2;
      Board board0 = null;
      try {
        board0 = new Board(2);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be greater or equals than 4.0
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(0, (-261));
      board_Position0.toString();
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board(0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: 0
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Board board0 = new Board();
      board0.hashCode();
      int int0 = (-3909);
      // Undeclared exception!
      try { 
        board0.getCell((-3909), 0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (-3909, 0) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      MockRNG mockRNG0 = new MockRNG(0.9);
      mockRNG0.getRandom();
      mockRNG0.getRandom();
      Board board0 = new Board(mockRNG0);
      mockRNG0.getRandom();
      mockRNG0.getRandom();
      board0.moveRight();
      board0.isWinningBoard();
      board0.hasEmptyCells();
      board0.getSize();
      board0.hasEmptyCells();
      board0.moveRight();
      board0.getSize();
      board0.moveDown();
      board0.moveRight();
      Board.Position board_Position0 = new Board.Position(4, 4);
      Cell cell0 = Cell.EMPTY;
      board0.moveLeft();
      // Undeclared exception!
      try { 
        board0.setCell(4, 0, cell0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (4, 0) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      int int0 = 3482;
      int int1 = 0;
      Board board0 = null;
      try {
        board0 = new Board(3482, 0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Winning value must be positive and not 0: 0
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      MockRNG mockRNG0 = new MockRNG();
      int int0 = 0;
      Board board0 = null;
      try {
        board0 = new Board(mockRNG0, 0, 110);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: 0
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      MockRNG mockRNG0 = new MockRNG();
      Board board0 = new Board(mockRNG0);
      // Undeclared exception!
      try { 
        board0.getCell(449, (-1099));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (449, -1099) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Board board0 = new Board(4);
      Board board1 = new Board(board0);
      board1.moveRight();
      board1.initializeEmptyTest();
      board0.moveDown();
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      Board board0 = new Board();
      board0.toString();
      board0.isWinningBoard();
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      Board board0 = new Board();
      board0.isFull();
      Cell cell0 = new Cell(2048);
      // Undeclared exception!
      try { 
        board0.setCell(4144, 0, cell0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (4144, 0) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      MockRNG mockRNG0 = new MockRNG();
      Board board0 = new Board(mockRNG0);
      board0.getScore();
      board0.hashCode();
      board0.equals(mockRNG0);
      board0.toString();
      mockRNG0.getRandom();
      board0.moveLeft();
      board0.getSize();
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      Board board0 = new Board(2, 2);
      Board board1 = new Board(board0);
      board1.repOK();
      board1.repOK();
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      MockRNG mockRNG0 = new MockRNG(0.0);
      Board board0 = new Board(mockRNG0);
      board0.isFull();
      mockRNG0.getRandom();
      mockRNG0.getRandom();
      board0.moveRight();
      board0.moveLeft();
      board0.moveLeft();
      mockRNG0.getRandom();
      board0.isFull();
      mockRNG0.getRandom();
      mockRNG0.getRandom();
      board0.isEmpty();
      board0.toString();
      board0.moveLeft();
      Cell cell0 = Cell.EMPTY;
      board0.setCell(0, 3, cell0);
      Board.Position board_Position0 = new Board.Position(2048, 0);
      Board board1 = null;
      try {
        board1 = new Board(2048, 0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Winning value must be positive and not 0: 0
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      Board board0 = new Board();
      board0.isEmpty();
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      MockRNG mockRNG0 = new MockRNG();
      Board board0 = null;
      try {
        board0 = new Board(mockRNG0, 2185, 0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Winning value must be positive and not 0: 0
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board((-1288), 0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: -1288
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board((-1973));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: -1973
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      Board board0 = new Board(1044);
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      Board board0 = new Board(32, 32);
      board0.isFull();
      board0.isLosingBoard();
      board0.isLosingBoard();
      board0.isEmpty();
      board0.repOK();
      board0.moveRight();
      Cell cell0 = new Cell(32);
      int int0 = Board.DEFAULT_WINNING_VALUE;
      board0.getScore();
      Random.setNextRandom(32);
      board0.moveRight();
      // Undeclared exception!
      board0.moveLeft();
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-167), 2232);
      board_Position0.toString();
      board_Position0.toString();
      Board.Position board_Position1 = new Board.Position((-167), (-167));
      board_Position1.toString();
      board_Position0.toString();
      board_Position0.toString();
      board_Position1.toString();
      board_Position0.equals(board_Position1);
      Board board0 = new Board();
      board0.moveDown();
      board0.isEmpty();
      assertFalse(board0.isEmpty());
      
      board0.initializeEmptyTest();
      board0.isLosingBoard();
      board0.equals(board0);
      assertEquals(0, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      Board board0 = new Board();
      board0.hasEmptyCells();
      board0.moveDown();
      board0.moveRight();
      int int0 = 1719;
      // Undeclared exception!
      try { 
        board0.getCell((-1), 1719);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (-1, 1719) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-167), (-167));
      board_Position0.toString();
      board_Position0.toString();
      Board.Position board_Position1 = new Board.Position((-167), (-167));
      board_Position1.toString();
      board_Position1.toString();
      String string0 = board_Position1.toString();
      assertEquals("(-167, -167)", string0);
      
      boolean boolean0 = board_Position0.equals(board_Position1);
      Board board0 = new Board();
      boolean boolean1 = board0.moveDown();
      assertTrue(boolean1 == boolean0);
      
      boolean boolean2 = board0.isEmpty();
      assertFalse(boolean2);
      
      board0.isFull();
      board0.getSize();
      boolean boolean3 = board0.isLosingBoard();
      assertEquals(2048, board0.winningValue);
      assertEquals(0, board0.getScore());
      assertFalse(boolean3);
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      Board board0 = new Board();
      Cell cell0 = new Cell(2048);
      board0.moveLeft();
      board0.setCell(3, 3, cell0);
      board0.isWinningBoard();
      board0.toString();
      board0.moveRight();
      board0.isLosingBoard();
      board0.isLosingBoard();
      // Undeclared exception!
      try { 
        board0.getCell(3, (-1431655765));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (3, -1431655765) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      Cell cell0 = new Cell(2048);
      MockRNG mockRNG0 = new MockRNG();
      Board board0 = new Board(mockRNG0, 481, 2048);
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-167), 2232);
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      Board.Position board_Position1 = new Board.Position((-167), (-167));
      board_Position1.toString();
      board_Position0.toString();
      board_Position1.toString();
      String string0 = board_Position1.toString();
      assertEquals("(-167, -167)", string0);
      
      board_Position0.equals(board_Position1);
      Board board0 = new Board();
      board0.moveDown();
      board0.moveDown();
      board0.hashCode();
      board0.getSize();
      assertFalse(board0.isEmpty());
      
      board0.initializeEmptyTest();
      board0.isLosingBoard();
      int int0 = Board.DEFAULT_WINNING_VALUE;
      Board board1 = new Board(board0);
      board0.equals(board1);
      board1.hasEmptyCells();
      boolean boolean0 = board0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      RNG rNG0 = new RNG();
      int int0 = 1660;
      rNG0.getRandom();
      rNG0.getRandom();
      Board board0 = null;
      try {
        board0 = new Board(rNG0, 1660, 1660);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Winning value must be a power of two: 1660
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board(2);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be greater or equals than 4.0
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      Board board0 = new Board();
      board0.hashCode();
      board0.hasEmptyCells();
      board0.getSize();
      board0.hasEmptyCells();
      board0.isWinningBoard();
      board0.initializeEmptyTest();
      board0.isEmpty();
      board0.getSize();
      board0.getScore();
      board0.moveDown();
      Random.setNextRandom(0);
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      Board board0 = new Board(1, 1);
      board0.isFull();
      board0.isLosingBoard();
      board0.isLosingBoard();
      board0.isEmpty();
      board0.repOK();
      board0.moveUp();
      int int0 = 2;
      // Undeclared exception!
      try { 
        board0.getCell(2, 1);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (2, 1) is out of bounds for board size 1
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test70()  throws Throwable  {
      MockRNG mockRNG0 = new MockRNG();
      mockRNG0.getRandom();
      mockRNG0.getRandom();
      Board board0 = null;
      try {
        board0 = new Board(mockRNG0, (-4448), 0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: -4448
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test71()  throws Throwable  {
      MockRNG mockRNG0 = new MockRNG();
      mockRNG0.getRandom();
      Board board0 = new Board(mockRNG0);
      boolean boolean0 = board0.hasEmptyCells();
      mockRNG0.getRandom();
      Board.Position board_Position0 = new Board.Position(4, 587);
      board_Position0.toString();
      board0.equals(mockRNG0);
      assertFalse(board0.isEmpty());
      
      mockRNG0.getRandom();
      board0.initializeEmptyTest();
      board0.moveLeft();
      board0.getEmptyPositions();
      board0.isLosingBoard();
      board0.getSize();
      board0.moveRight();
      boolean boolean1 = board_Position0.equals(board_Position0);
      assertTrue(boolean1 == boolean0);
  }

  @Test(timeout = 4000)
  public void test72()  throws Throwable  {
      MockRNG mockRNG0 = new MockRNG();
      mockRNG0.getRandom();
      mockRNG0.getRandom();
      Board board0 = new Board(mockRNG0);
      mockRNG0.getRandom();
      board0.isWinningBoard();
      board0.moveUp();
      Cell cell0 = board0.getCell(0, 0);
      board0.setCell(0, 0, cell0);
      mockRNG0.getRandom();
      mockRNG0.getRandom();
      // Undeclared exception!
      try { 
        board0.getCell(0, 1511);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (0, 1511) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test73()  throws Throwable  {
      Board board0 = new Board(4);
      board0.isEmpty();
      board0.toString();
      board0.moveUp();
      board0.moveDown();
      board0.moveLeft();
      Board.Position board_Position0 = new Board.Position(4, 4);
      board0.moveRight();
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.equals("Score: 0\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n|    2|    2|     |     |\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n");
      board0.moveUp();
      board0.moveDown();
      board0.repOK();
      board0.isLosingBoard();
      board0.moveRight();
      board_Position0.toString();
      MockRNG mockRNG0 = null;
      try {
        mockRNG0 = new MockRNG((-726.6));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Value must be between 0 and 1
         //
         verifyException("ar.edu.unrc.game2048.MockRNG", e);
      }
  }
}
